"""Initial migration

Revision ID: a09d78c30470
Revises: 
Create Date: 2025-11-05 20:26:11.689562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09d78c30470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dishes_pkey'))
    )
    op.create_index(op.f('dishes_created_at_idx'), 'dishes', ['created_at'], unique=False)
    op.create_index(op.f('dishes_id_idx'), 'dishes', ['id'], unique=False)
    op.create_index(op.f('dishes_name_idx'), 'dishes', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('dishes_name_idx'), table_name='dishes')
    op.drop_index(op.f('dishes_id_idx'), table_name='dishes')
    op.drop_index(op.f('dishes_created_at_idx'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
